use teste; 
show tables; /*MOSTRA AS TABELAS EXISTENTES*/

create table produtos (id int PRIMARY KEY AUTO_INCREMENT, /*CRIAÇÃO DA TABELA*/
NOME VARCHAR(100) NOT NULL, 
DESCRICAO TEXT, 
PRECO DECIMAL(10,2), 
QUANTIDADE INT default(0), 
DATA_ENTRADA DATE default current_timestamp);

select * FROM produtos; /*VISUALIZAÇÃO DA TABELA*/

INSERT INTO produtos (NOME, DESCRICAO, PRECO, QUANTIDADE, DATA_ENTRADA)/*INSERÇÃO DE DADOS DA TABELA*/
VALUES ("ARROZ", "ARROZ TIPO BRANCO", "29.90", "17", "2025/08/04");
INSERT INTO produtos (NOME, DESCRICAO, PRECO, QUANTIDADE, DATA_ENTRADA)
VALUES ("FEIJÃO", "FEIJÃO CARIOCA", "7.90", "30", "2025/12/09");
INSERT INTO produtos (NOME, DESCRICAO, PRECO, QUANTIDADE, DATA_ENTRADA)
VALUES ("FRANGO", "FRANGO ASSADO", "20.78","28", "2025/02/24");

select * FROM produtos;

update PRODUTOS SET PRECO="9.65" WHERE ID=3;/*ATUALIZA A TABALA PRODUTOS NA PARTE DE PREÇO PARA 9.65 ONDE O ID FOR IGUAL A 3*/
update PRODUTOS SET QUANTIDADE="09" WHERE ID=1;/*ATUALIZA A TABALA PRODUTOS NA PARTE DE QUANTIDADE PAA 09 ONDE O ID FOR IGUAL A 1*/
DELETE FROM PRODUTOS WHERE ID=4;/*DELETA DA TABELA PRODUTOS ONDE O ID FOR IGUAL A 4*/
select * FROM PRODUTOS WHERE PRECO >10;/*MOSTRA SOMENTE PRODUTOS COM PRECO ACIMA DE 10 REAIS*/
select * FROM PRODUTOS WHERE NOME LIKE "C%";/*MOSTRA OS ELEMENTOS DA TABELA PRODUTO APENAS ONDE TEM NOME COMEÇADO EM C*/
SELECT NOME, PRECO FROM PRODUTOS;/*MOSTRA O NOME E O PRECO DE TODOS OS ITENS DA TABELA PRODUTOS*/
